# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C',
        ),
    ]
