# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170714_1813'),
        ('users', '0003_remove_myuser_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='defaultBlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
    ]
