# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_defaultblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='defaultBlog',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
