# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170714_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='defaultBlog',
            field=models.IntegerField(null=True),
        ),
    ]
