# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_g'),
    ]

    operations = [
        migrations.DeleteModel(
            name='G',
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
