# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170715_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_image_path),
        ),
    ]
