# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='choice_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
