# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170714_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 15, 22, 34, 28, 231148)),
        ),
    ]
